// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path=".snaplet/snaplet.d.ts" />
// This config was generated by Snaplet make sure to check it over before using it.
import { copycat, faker } from "@snaplet/copycat";
import { defineConfig } from "snaplet";
export default defineConfig({
  transform: {
    public: {
      actions({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 255,
          }),
        };
      },
      admins({ row }) {
        return {
          email: copycat.email(row.email, {
            limit: 255,
          }),
          name: copycat.fullName(row.name, {
            limit: 100,
          }),
        };
      },
      base_attachments({ row }) {
        return {
          name: copycat.fullName(row.name, {
            limit: 255,
          }),
        };
      },
      cart_shipment_arta_quote_services({ row }) {
        return {
          name: copycat.fullName(row.name),
          subtype: copycat.scramble(row.subtype),
        };
      },
      carts({ row }) {
        return {
          email: copycat.email(row.email, {
            limit: 255,
          }),
          phone: copycat.scramble(row.phone),
          full_name: copycat.username(row.full_name, {
            limit: 255,
          }),
          city: copycat.scramble(row.city),
          zip_code: copycat.scramble(row.zip_code, {
            preserve: ["#", "-"],
          }),
        };
      },
      categories({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 100,
          }),
        };
      },
      checkouts({ row }) {
        return {
          email: copycat.email(row.email, {
            limit: 255,
          }),
        };
      },
      client_addresses({ row }) {
        return {
          first_name: copycat.firstName(row.first_name, {
            limit: 100,
          }),
          last_name: copycat.lastName(row.last_name, {
            limit: 100,
          }),
          city: copycat.scramble(row.city),
          zip_code: copycat.scramble(row.zip_code, {
            preserve: ["#", "-"],
          }),
          phone: copycat.scramble(row.phone),
        };
      },
      client_expert_availability_subscriptions({ row }) {
        return {
          email: copycat.email(row.email, {
            limit: 255,
          }),
        };
      },
      clients({ row }) {
        return {
          first_name: copycat.firstName(row.first_name, {
            limit: 100,
          }),
          last_name: copycat.lastName(row.last_name, {
            limit: 100,
          }),
          timezone: copycat.scramble(row.timezone),
          phone_number: copycat.scramble(row.phone_number),
        };
      },
      cms_alphabetical_index_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 255,
          }),
        };
      },
      cms_article_heading_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
          caption: copycat.scramble(row.caption),
        };
      },
      cms_article_pages({ row }) {
        return {
          tag: copycat.scramble(row.tag),
        };
      },
      cms_articles_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
          subtitle: copycat.fullName(row.subtitle, {
            limit: 200,
          }),
        };
      },
      cms_banner_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
        };
      },
      cms_card_navigation_widget_items({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
        };
      },
      cms_card_navigation_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
          subtitle: copycat.fullName(row.subtitle, {
            limit: 200,
          }),
        };
      },
      cms_category_collection_widget_items({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
        };
      },
      cms_category_collection_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
          subtitle: copycat.fullName(row.subtitle, {
            limit: 200,
          }),
        };
      },
      cms_category_header_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
          subtitle: copycat.fullName(row.subtitle, {
            limit: 200,
          }),
        };
      },
      cms_collection_header_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 40,
          }),
          subtitle: copycat.fullName(row.subtitle, {
            limit: 100,
          }),
        };
      },
      cms_collections_carousel_widget_items({ row }) {
        return {
          caption: copycat.sentence(row.caption),
        };
      },
      cms_collections_carousel_widgets({ row }) {
        return {
          title: copycat.fullName(row.title),
          subtitle: copycat.fullName(row.subtitle),
        };
      },
      cms_consultation_listing_widgets({ row }) {
        return {
          duration: copycat.scramble(row.duration),
        };
      },
      cms_expert_collections_widget_items({ row }) {
        return {
          caption: copycat.sentence(row.caption),
        };
      },
      cms_experts_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
        };
      },
      cms_gallery_widget_items({ row }) {
        return {
          caption: copycat.sentence(row.caption),
        };
      },
      cms_gallery_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
        };
      },
      cms_gift_card_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 255,
          }),
        };
      },
      cms_hero_carousel_widget_items({ row }) {
        return {
          pre_title: copycat.fullName(row.pre_title, {
            limit: 100,
          }),
        };
      },
      cms_hero_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
        };
      },
      cms_introduction_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
          pretitle: copycat.fullName(row.pretitle, {
            limit: 200,
          }),
          posttitle: copycat.fullName(row.posttitle, {
            limit: 200,
          }),
        };
      },
      cms_listing_widgets({ row }) {
        return {
          name: copycat.fullName(row.name, {
            limit: 200,
          }),
        };
      },
      cms_multi_collection_widget_items({ row }) {
        return {
          caption: copycat.sentence(row.caption),
        };
      },
      cms_pages({ row }) {
        return {
          slug: copycat.scramble(row.slug, {
            preserve: [],
          }),
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
        };
      },
      cms_products_widget_items({ row }) {
        return {
          title: copycat.fullName(row.title),
          pretitle: copycat.fullName(row.pretitle),
          posttitle: copycat.fullName(row.posttitle),
        };
      },
      cms_single_image_widgets({ row }) {
        return {
          caption: copycat.sentence(row.caption),
        };
      },
      cms_spotlight_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
          sub_title: copycat.fullName(row.sub_title, {
            limit: 200,
          }),
        };
      },
      cms_testimonials_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
        };
      },
      cms_video_section_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
          subtitle: copycat.fullName(row.subtitle, {
            limit: 200,
          }),
        };
      },
      cms_video_widgets({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 200,
          }),
        };
      },
      collections({ row }) {
        return {
          title: copycat.fullName(row.title),
        };
      },
      commissions({ row }) {
        return {
          rate: copycat.float(row.rate, {
            max: Math.pow(2, 4),
          }),
        };
      },
      credit_transactions({ row }) {
        return {
          note: copycat.fullName(row.note),
          rate: copycat.float(row.rate, {
            max: Math.pow(2, 4),
          }),
        };
      },
      currency_rates({ row }) {
        return {
          rate: copycat.float(row.rate, {
            max: Math.pow(2, 4),
          }),
        };
      },
      expert_applications({ row }) {
        return {
          first_name: copycat.firstName(row.first_name, {
            limit: 100,
          }),
          last_name: copycat.lastName(row.last_name, {
            limit: 100,
          }),
          email: copycat.email(row.email, {
            limit: 255,
          }),
          birth_date: copycat
            .dateString(row.birth_date, {
              minYear: 1950,
              maxYear: 2000,
            })
            .slice(0, 10),
          city: copycat.scramble(row.city),
        };
      },
      expert_sessions({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 100,
          }),
        };
      },
      expert_user_notification_emails({ row }) {
        return {
          email: copycat.email(row.email, {
            limit: 255,
          }),
        };
      },
      expert_users({ row }) {
        return {
          email: copycat.email(row.email, {
            limit: 255,
          }),
          title: copycat.fullName(row.title, {
            limit: 255,
          }),
          first_name: copycat.firstName(row.first_name, {
            limit: 100,
          }),
          last_name: copycat.lastName(row.last_name, {
            limit: 100,
          }),
          timezone: copycat.scramble(row.timezone),
          new_email: copycat.email(row.new_email, {
            limit: 255,
          }),
        };
      },
      expert_videos({ row }) {
        return {
          caption: copycat.scramble(row.caption),
        };
      },
      experts({ row }) {
        return {
          email: copycat.email(row.email, {
            limit: 255,
          }),
          birth_date: copycat
            .dateString(row.birth_date, {
              minYear: 1950,
              maxYear: 2000,
            })
            .slice(0, 10),
          city: copycat.scramble(row.city),
          job_title: copycat.fullName(row.job_title),
          slug: copycat.scramble(row.slug, {
            preserve: [],
          }),
        };
      },
      external_product_previews({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 255,
          }),
        };
      },
      feature_flags({ row }) {
        return {
          label: copycat.fullName(row.label, {
            limit: 255,
          }),
        };
      },
      files_and_notes_items({ row }) {
        return {
          note: copycat.fullName(row.note),
        };
      },
      guest_users({ row }) {
        return {
          email: copycat.email(row.email, {
            limit: 255,
          }),
        };
      },
      knex_migrations({ row }) {
        return {
          name: copycat.fullName(row.name, {
            limit: 255,
          }),
          batch: copycat.int(row.batch, {
            min: 0,
            max: Math.pow(4, 8) - 1,
          }),
        };
      },
      navigation_groups({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 255,
          }),
        };
      },
      navigation_items({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 255,
          }),
        };
      },
      navigations({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 255,
          }),
        };
      },
      order_notes({ row }) {
        return {
          message: copycat.state(row.message),
        };
      },
      order_shipment_arta_quote_services({ row }) {
        return {
          name: copycat.fullName(row.name),
          subtype: copycat.scramble(row.subtype),
        };
      },
      product_attributes({ row }) {
        return {
          name: copycat.fullName(row.name),
          value: copycat.fullName(row.value),
        };
      },
      product_categories({ row }) {
        return {
          name: copycat.fullName(row.name, {
            limit: 100,
          }),
        };
      },
      product_custom_fields({ row }) {
        return {
          name: copycat.fullName(row.name),
          value: copycat.fullName(row.value),
        };
      },
      product_options({ row }) {
        return {
          name: copycat.fullName(row.name, {
            limit: 255,
          }),
        };
      },
      product_variant_custom_fields({ row }) {
        return {
          name: copycat.fullName(row.name),
          value: copycat.fullName(row.value),
        };
      },
      product_variant_option_values({ row }) {
        return {
          value: copycat.fullName(row.value, {
            limit: 255,
          }),
        };
      },
      product_variants({ row }) {
        return {
          sku: copycat.uuid(row.sku),
          title: copycat.fullName(row.title),
        };
      },
      products({ row }) {
        return {
          sku: copycat.uuid(row.sku),
          title: copycat.fullName(row.title),
        };
      },
      promo_codes({ row }) {
        return {
          start: copycat.dateString(row.start, {
            minYear: 2020,
          }),
        };
      },
      regions({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 100,
          }),
        };
      },
      roles({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 255,
          }),
        };
      },
      session_report_items({ row }) {
        return {
          title: copycat.fullName(row.title),
          note: copycat.fullName(row.note),
        };
      },
      session_reports({ row }) {
        return {
          note: copycat.fullName(row.note),
        };
      },
      sources({ row }) {
        return {
          city: copycat.city(row.city),
          state: copycat.state(row.state),
          state_code: copycat.sentence(row.state_code),
          country: copycat.country(row.country),
          country_code: copycat.countryCode(row.country_code),
          postal: copycat.state(row.postal),
          email: copycat.email(row.email),
          phone: copycat.phoneNumber(row.phone),
          first_name: copycat.firstName(row.first_name),
          last_name: copycat.lastName(row.last_name),
          name: copycat.fullName(row.name, {
            limit: 255,
          }),
        };
      },
      tags({ row }) {
        return {
          title: copycat.fullName(row.title),
        };
      },
      trusted_sources({ row }) {
        return {
          domain: copycat.email(row.domain, {
            limit: 255,
          }),
        };
      },
      vendors({ row }) {
        return {
          name: copycat.fullName(row.name, {
            limit: 200,
          }),
        };
      },
      video_attachments({ row }) {
        return {
          name: copycat.fullName(row.name, {
            limit: 255,
          }),
        };
      },
    },
  },
});
