name: Database Snapshot

on:
  push:
    branches:
      - main

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.12.1

    - name: Install dependencies
      # TODO: remove force
      run: cd api && npm install --force

    - name: Capture Database Snapshot
      env:
        SNAPLET_SOURCE_DATABASE_URL: ${{ secrets.SNAPLET_SOURCE_DATABASE_URL }}
      run: cd api && npx snaplet snapshot capture

    - name: Find and Compress Newest Snapshot
      run: |
        # Find the newest snapshot directory in .snaplet/snapshots
        newest_snapshot_dir=$(find api/.snaplet/snapshots -type d -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d' ')
        echo "Newest snapshot directory: $newest_snapshot_dir"
        # Create a tar.gz archive of the newest snapshot
        tar -czvf production_db_snapshot.tar.gz -C "$newest_snapshot_dir" .

    - name: Upload report to CDN
      env:
        BUNNY_CDN_CI_ARCHIVE_API_KEY: ${{secrets.BUNNY_CDN_CI_ARCHIVE_API_KEY}}
        BUNNY_CDN_STORAGE_ZONE_NAME: theexpert-dev-public
      run: |
        node ${{github.workspace}}/.github/workflows/uploadSnapshotToCdn
