name: Database Snapshot

# run on every push to main
on:
  push:
    branches:
      - main


jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Go to api directory
      run: cd api

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.12.1

    - name: Install dependencies
      run: npm install

    - name: Capture Database Snapshot
      env:
        SNAPLET_SOURCE_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/the_expert_dev
      run: npx snaplet snapshot capture

    - name: Create Tar Gz from Snapshot
      run: tar -czvf snapshot/production_db_snapshot.tar.gz snapshot/

    - name: Upload Snapshot Artifact
      uses: actions/upload-artifact@v2
      with:
        name: database-snapshot
        path: snapshot/production_db_snapshot.tar.gz
